name: deploy-javascript

on:
  push:
    branches:
      - main
    paths:
      - javascript/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: javascript

    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Move files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ../docs/javascript
